export addMissle from './add-missle'
export setCanvas from './set-canvas'
export setGame from './set-game'
export setLayout from './set-layout'
export setMissles from './set-missles'
export setShip from './set-ship'
export * as TYPES from './types'
