export const ADD_MISSLE = 'add-missle'
export const SET_CANVAS = 'set-canvas'
export const SET_GAME = 'set-game'
export const SET_LAYOUT = 'set-layout'
export const SET_MISSLES = 'set-missles'
export const SET_SHIP = 'set-ship'
